### ISSUE TITLE
Undeclared variables in qc_pvca

### ISSUE THREAD

**Issue by zsigmas** [uebvhir/maUEB#3]
https://github.com/uebvhir/maUEB/blob/00a05302032f42f2ab9ea0c1d6cec2a373d208e8/R/qc_pvca.R#L25

This line relies on undeclared parameters inside the function, `targets.pvcaFN` and `targetsFN`.

When rendering the rmd file all works fine because those variables are declared in the caller environment.
https://github.com/uebvhir/maUEB/blob/901c258411fa2ce18eef36569765dc44b1a66bf7/vignettes/Example_microarray_analysis_2.Rmd#L348

Nonetheless when those are used elsewhere it will very likely cause problems.

These variables should very likely be passed as arguments to the function.

----

Additionally `&&` is preferred in `if` clauses over `&`.

See R doc (https://stat.ethz.ch/R-manual/R-devel/library/base/html/Logic.html):

> & and && indicate logical AND and | and || indicate logical OR. The shorter forms performs elementwise comparisons in much the same way as arithmetic operators. The longer forms evaluates left to right, proceeding only until the result is determined. The longer form is appropriate for programming control-flow and typically preferred in [if](vscode-webview://16otfpjcgnugqivgi740f8ub86ar375i6rhiuesc98a0j7preqtn/base/help/if) clauses.

**Comment by zsigmas** [comment]
A similar issue happens with the variable resultDir in:
https://github.com/uebvhir/maUEB/blob/fa712b2cf64a95c2275e68fe7b0853e56f94ce65/R/dea_toptab.R#L64

resultsDir is not declared in the function, very likely it should be replaced bu outputDir

**Comment by zsigmas** [comment]
Same in https://github.com/uebvhir/maUEB/blob/9967852f3657f83efa6f958c1659e4baa8c22a38/R/mc_venn_upset.R#L85

`venn_comparNames`

**Comment by mferrer-almirall** [comment]
Many thanks for the comments, fixed and uploaded changes!
